name: ulrm
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - arc-alkali-rydberg-calculator==3.8.1
      - asteval==1.0.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dill==0.4.0
      - fonttools==4.58.1
      - h5py==3.13.0
      - kiwisolver==1.4.8
      - lmfit==1.3.3
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - numpy==2.2.6
      - packaging==25.0
      - pillow==11.2.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - rich==14.0.0
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - uncertainties==3.2.3
prefix: /Users/user/anaconda3/envs/ulrm
